apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: tasksphere-app-monitor
  labels:
    app: tasksphere-backend
spec:
  selector:
    matchLabels:
      app: tasksphere-backend-Service # Matches the label of your Node.js application's Service
  endpoints:
    - port: http # The name of the port exposed by your Node.js application's Service
      path: /metrics
      interval: 15s # How often Prometheus should scrape metrics
