apiVersion: v1
kind: Service
metadata:
  name: tasksphere-backend-service

spec:
  selector:
    app: tasksphere-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 5000
  type: ClusterIP
