apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  type: NodePort
  selector:
    app: tasksphere-frontend # This should match the label of your frontend pods
  ports:
    - protocol: TCP
      port: 80 # The port the service will listen on inside the cluster
      targetPort: 3000 # The port your frontend application is listening on in the pod
      nodePort: 30007 # Optional: A specific NodePort in the range 30000-32767. If omitted, Kubernetes assigns one.
