apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasksphere-deployment
  namespace: postgres-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasksphere-backend
  template:
    metadata:
      labels:
        app: tasksphere-backend
    spec:
      containers:
        - name: nodejs-backend
          image: ayoub46/tasksphere-backend:latest
          env:
            - name: DB_HOST
              value: postgres-service
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD
            - name: DB_NAME
              value: tasksphere
          ports:
            - containerPort: 5000
